---
- name: Install Cordova
  npm: >
   name=cordova
   state=present
   global=yes
   version={{ cordova_version }}
  tags: ionic
  sudo: yes

- name: Install Ionic
  npm: >
   name=ionic
   state=present
   global=yes
   version={{ ionic_version }}
  tags: ionic
  sudo: yes
